### ISSUE TITLE
Store Feature

### ISSUE THREAD

**Issue by superterran** [trinaisartsy/github.io#42]
We want to build out a store, separate from the gallery

https://projects.invisionapp.com/d/main#/console/14362913/298728194/preview

**Comment by trinaisartsy** [comment]
![image](https://user-images.githubusercontent.com/35178942/45587286-dcfc5480-b8d1-11e8-848f-91d74e59a482.png)

**Comment by trinaisartsy** [comment]
Note:

To keep the gallery different from the shop, only the very best pieces will be added to the shop, possibly by a different tag. Also, the shop will include craft items, which should not be included in the main gallery.
